"""End-to-end demo: oh (OpenHarness) → LLM → save content → ready for ljg-card.

Demonstrates the "结合使用" (combined use) path:
    OpenHarness skill (ljg-openharness) calls `oh` CLI
        → `oh` invokes LLM (minimax M3 by default)
            → output written to ~/Downloads/ljg-openharness-demo-<ts>.md
                → user (or Claude Code) hands content to ljg-card for PNG render

Usage:
    python3 examples/oh_to_card.py
    python3 examples/oh_to_card.py "Write a haiku about AI agents"
"""
from __future__ import annotations
import sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from lib import prompt  # noqa: E402


PROMPT_DEFAULT = (
    "用中文写一段关于「为什么 AI agent 应该永远记得它的主人」的短文。"
    "3-5 句话，不要 markdown，纯文本。"
)


def main() -> int:
    user_prompt = sys.argv[1] if len(sys.argv) > 1 else PROMPT_DEFAULT

    print(f"[ljg-openharness demo] prompting oh...")
    text = prompt(user_prompt, output_format="text", timeout=60)

    if not text or not text.strip():
        print("ERROR: oh returned empty output", file=sys.stderr)
        return 1

    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    out_path = Path.home() / "Downloads" / f"ljg-openharness-demo-{ts}.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        f"# OpenHarness demo · {ts}\n\n"
        f"## Prompt\n\n{user_prompt}\n\n"
        f"## oh LLM output\n\n{text.strip()}\n\n"
        f"---\n"
        f"_generated by ljg-openharness · "
        f"hand off to ljg-card -v / -w / -l to render as PNG_\n",
        encoding="utf-8",
    )
    print(f"OK · wrote {out_path} ({len(text)} chars)")
    print(f"\n--- preview ---\n{text.strip()[:200]}...")
    return 0


if __name__ == "__main__":
    sys.exit(main())